server:
    port: ${port:8760}
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-shengchan

spring:
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wangfei?characterEncoding=utf-8
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

